### ISSUE TITLE
Roadmap v5.0

### ISSUE THREAD

**Issue by WyriHaximus** [WyriHaximus/TwigView#88]
Todo:
- [x] Twig 3.0
- [x] Bump minimum PHP version to `7.1`
- [x] Merge in all changes from the `4.x` branch
- [x] Clean up and reorganize filters and functions 

Research:
- [X] Disable autoescaping for functions and filters so `|raw` everywhere isn't required (via @markstory)

**Comment by inoas** [comment]
Targeting CakePHP 4.0 (or 3.7) only?

**Comment by WyriHaximus** [comment]
Probably CakePHP 4.0, but if 3.7 isn't to much of an hassle that would be awesome. The thing is I would prefer to support the same minimum PHP version as CakePHP 4.0 with this 5.0 release.

**Comment by WyriHaximus** [comment]
@ADmad && @markstory Any things on cake's wishlist for 5.0 (targeting cakephp 4.0)?

**Comment by markstory** [comment]
I would love to help find a way to not need `|raw` all over the place. I find it noisy and trains people to use `|raw` which can be dangerous.

**Comment by WyriHaximus** [comment]
@markstory looking into how to sanely do that :+1:

**Comment by ADmad** [comment]
Just skimming through twig docs I couldn't find a way to tell twig to disable escape for specific vars used in `{{ }}`.

So avoiding the need for using `|raw` would probably require registering new tag for helpers as it's done for cells and element. Usage would be like `{% helper 'Foo.method' %}`. This would make the usage a bit more verbose but on the flip side it would provide the benefit of being able to use helper auto loading like we have for `.ctp` files. Currently you need to explicitly load the helpers you want to use in twig template.

**Comment by WyriHaximus** [comment]
There might be something deeper in the API to do this, not entirely sure.

Like the idea, not 100% sold on the syntax but I'll get an experiment on this weekend to implement it and see where we can take it from there :+1: .

**Comment by markstory** [comment]
@ADmad TwigView could use reflection to generate twig functions for all defined helper methods. Twig functions can indicate that they are escapers. This would add a bit of overhead but could be something that is 'compiled' or cached.

**Comment by ADmad** [comment]
@markstory Yeah using reflection in `TwigView` is an option but I would prefer if the additional work could be done through Twig itself instead of adding reflection in our view class.

On a related note could be shorten the tag for `element` to `elem`? :)

**Comment by ADmad** [comment]
Having helpers as regular variables also has the drawback that if someone doesn't follow conventions and for e.g. sets a view vars named `Html`, the variable will be overwritten by helper instance.

**Comment by WyriHaximus** [comment]
> On a related note could be shorten the tag for `element` to `elem`? :)

Sure, could probably do both 😜

**Comment by WyriHaximus** [comment]
@ADmad just been digging around and found this: https://twig.symfony.com/doc/2.x/advanced.html#automatic-escaping 
We could/should select specific functions and filters that will be safe to be output rawly into the resulting template

**Comment by markstory** [comment]
@WyriHaximus Yes, that would be really useful on Helper proxy functions.

**Comment by WyriHaximus** [comment]
Merging `4.x` in `master` now:

![image](https://user-images.githubusercontent.com/147145/43422122-0ede260c-9449-11e8-82f0-b07e40643219.png)


Will keep you updated, and tag you in relevant PR's for the extra tags and escaping

**Comment by ADmad** [comment]
I was looking into updating `master` to run with CakePHP 4 and got stuck. There's a bit of chicken and egg problem as Bake requires TwigView and TwigView itself has Bake as `required-dev` :slightly_smiling_face:

I tried to work on TwigView first ignoring the Bake dependency but the 1st blocker is the `api-clients/test-utilities`.  Cake 4 requires PHP 7.1+ and phpunit 7.0+ but there's no version of `test-utilities` which satisfies these dependencies.

**Comment by ADmad** [comment]
As always "When it's ready" :)

**Comment by WyriHaximus** [comment]
> As always "When it's ready" :)

Cool, the underlying question was: How fast does this needs to be done. But I'll get onto some stuff after my Honeymoon and dedicate some days to straightening things out and get them CakePHP 4 ready :+1: .

**Comment by ADmad** [comment]
No worries. Congrats on your wedding and enjoy your honeymoon :slightly_smiling_face:

**Comment by WyriHaximus** [comment]
Thank you, enjoying it a lot :sunglasses: !

**Comment by FinlayDaG33k** [comment]
I've been taking a look at this repo lately because we are considering to implement this in our project, however, I feel like it's "odd" to have to rename all the `.ctp` files to `.twig` files to use TwigView.  
I wonder if it would be possible to use the regular `.ctp` files instead?

**Comment by ADmad** [comment]
@FinlayDaG33k "regular" .ctp files contain PHP code :). Why would you unnecessarily confuse anyone dev joining your project by using .ctp extension instead of the default .twig for Twig files?

**Comment by WyriHaximus** [comment]
It's not only that, `TwigView` will fallback to `.ctp` files if it can't find the matching `.twig` file. So both formats are supported and you can iterate your way into support it file by file. There are  also some IDE benefits such as PHPStorm picking up it's a twig file without having to configure that.

**Comment by FinlayDaG33k** [comment]
> Why would you unnecessarily confuse any new dev joining your project by using .ctp extension instead of the default .twig for Twig files?

Well, to me, it feels more confusing that everything is `.ctp` and then suddenly there are some `.twig` files hanging around.

> It's not only that, TwigView will fallback to .ctp files if it can't find the matching .twig file.
Ah I see.  
This wasn't in the documentation, I'll add that in a bit :)

**Comment by WyriHaximus** [comment]
> > It's not only that, TwigView will fallback to .ctp files if it can't find the matching .twig file.
> > Ah I see.
> 
> This wasn't in the documentation, I'll add that in a bit :)

Cool :+1: !

**Comment by dereuromark** [comment]
the files should be whatever they are. so if those are twig templates, then the file extension should be .twig.
this also makes it able to leverage IDEs here to introspect them more easily.

As for the new Cake4 release, any plans on releasing a beta already or sth?
https://github.com/cakephp/bake/blob/master/composer.json#L24

    "wyrihaximus/twig-view": "dev-master"

this is blocking other plugins to become stable.

> cakephp/bake 2.0.1 requires wyrihaximus/twig-view dev-master -> satisfiable by wyrihaximus/twig-view[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by dereuromark** [comment]
PS: Once you got a beta tag out, like the other plugins now, you can add the strawberry: https://github.com/FriendsOfCake/awesome-cakephp/pull/334 :)

**Comment by WyriHaximus** [comment]
@dereuromark Hopefully this weekend. Will let you know once the tag is out

**Comment by WyriHaximus** [comment]
[`5.0`](https://github.com/WyriHaximus/TwigView/releases/tag/5.0.0) is out :tada:
